/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.baimaytinhbotui;

/**
 *
 * @author Administrator
 */
public class calculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form calculatorForm
     */
    public calculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnnumber1 = new javax.swing.JButton();
        btnnumber2 = new javax.swing.JButton();
        btnnumber3 = new javax.swing.JButton();
        btnchia = new javax.swing.JButton();
        btnsqrt = new javax.swing.JButton();
        btnnumber4 = new javax.swing.JButton();
        btnnumber5 = new javax.swing.JButton();
        btnnumber6 = new javax.swing.JButton();
        btnnhan = new javax.swing.JButton();
        btnphantram = new javax.swing.JButton();
        btnnumber7 = new javax.swing.JButton();
        btnnumber8 = new javax.swing.JButton();
        btnnumber9 = new javax.swing.JButton();
        btncong = new javax.swing.JButton();
        btn1trenx = new javax.swing.JButton();
        btnnumber0 = new javax.swing.JButton();
        btnFlush = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btntru = new javax.swing.JButton();
        btnbang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CASIO");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.GridLayout(4, 5, 5, 5));

        btnnumber1.setText("1");
        btnnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnumber1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnnumber1);

        btnnumber2.setText("2");
        jPanel2.add(btnnumber2);

        btnnumber3.setText("3");
        jPanel2.add(btnnumber3);

        btnchia.setText("/");
        jPanel2.add(btnchia);

        btnsqrt.setText("sqrt");
        jPanel2.add(btnsqrt);

        btnnumber4.setText("4");
        jPanel2.add(btnnumber4);

        btnnumber5.setText("5");
        jPanel2.add(btnnumber5);

        btnnumber6.setText("6");
        jPanel2.add(btnnumber6);

        btnnhan.setText("*");
        jPanel2.add(btnnhan);

        btnphantram.setText("%");
        jPanel2.add(btnphantram);

        btnnumber7.setText("7");
        jPanel2.add(btnnumber7);

        btnnumber8.setText("8");
        jPanel2.add(btnnumber8);

        btnnumber9.setText("9");
        jPanel2.add(btnnumber9);

        btncong.setText("+");
        jPanel2.add(btncong);

        btn1trenx.setText("1/x");
        jPanel2.add(btn1trenx);

        btnnumber0.setText("0");
        jPanel2.add(btnnumber0);

        btnFlush.setText("+/-");
        jPanel2.add(btnFlush);

        btnClear.setText("C");
        jPanel2.add(btnClear);

        btntru.setText("-");
        jPanel2.add(btntru);

        btnbang.setText("=");
        jPanel2.add(btnbang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnumber1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1trenx;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFlush;
    private javax.swing.JButton btnbang;
    private javax.swing.JButton btnchia;
    private javax.swing.JButton btncong;
    private javax.swing.JButton btnnhan;
    private javax.swing.JButton btnnumber0;
    private javax.swing.JButton btnnumber1;
    private javax.swing.JButton btnnumber2;
    private javax.swing.JButton btnnumber3;
    private javax.swing.JButton btnnumber4;
    private javax.swing.JButton btnnumber5;
    private javax.swing.JButton btnnumber6;
    private javax.swing.JButton btnnumber7;
    private javax.swing.JButton btnnumber8;
    private javax.swing.JButton btnnumber9;
    private javax.swing.JButton btnphantram;
    private javax.swing.JButton btnsqrt;
    private javax.swing.JButton btntru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
